"""
Django settings for vermillion_player project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import admin

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z@ng59=n-vu+-h4(@mvxc_)+y(ti1(1*4qj3-i1a+pwl-sf36n"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "graphene_django",
    "core",
    "channel",
    "program",
    "movie"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "vermillion_player.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vermillion_player.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-ES"

TIME_ZONE = "Europe/Madrid"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

GRAPHENE = {
    "SCHEMA": "core.schema.schema"
}

JAZZMIN_SETTINGS = {
    "site_title": "Vermillion Player",
    "site_logo": "img/logo.png",  
    "site_logo_classes": "img-circle", 
    "welcome_sign": "Bienvenido a Vermillion Player",
    "site_header": "Panel de control",
    "site_brand": "Vermillion Player",
    "copyright": "Pytonicus - GNU GENERAL PUBLIC LICENSE Version 3",
    "show_sidebar": True,
    "search_model": ["movie.Movie", "program.Program"],

    "topmenu_links": [
        {"model": "auth.User"},
        {"app": "movie"},
        {"app": "program"},
        {"name": "CDN", "url": "http://127.0.0.1:5000", "new_window": True}
    ],
    "usermenu_links": [
        {"name": "CDN", "url": "http://127.0.0.1:5000", "new_window": True},
        {"model": "auth.user"}
    ],

    "order_with_respect_to": ["auth", "core", "channel", "movie", "program"],

    "custom_links": {
        "program": [{
            "name": "Subir episodios", 
            "url": "http://127.0.0.1:5000", 
            "icon": "fas fa-cloud"
        }
        ]
    },

    "icons": {
        "core.actor": "fas fa-theater-masks",
        "core.category": "fas fa-folder-open",
        "channel.channel": "fas fa-tv",
        "movie.movie": "fas fa-film",
        "program.program": "fas fa-clapperboard",
        "program.season": "fas fa-list-ol",
        "program.episodes": "fas fa-play-circle"
    },

}