name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: vermillion
          POSTGRES_USER: vermillion
          POSTGRES_PASSWORD: vermillion
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U vermillion" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      DJANGO_DB_HOST: localhost
      DJANGO_DB_NAME: vermillion
      DJANGO_DB_USER: vermillion
      DJANGO_DB_PASSWORD: vermillion
      DJANGO_DB_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t vermillion-admin-panel .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -U vermillion; do
            sleep 1
          done

      - name: Run migrations and collectstatic
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Run unit tests
        run: pytest --cov --cov-config=.coveragerc